version: '3.6'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command:
      redis-server
    networks:
      - ship
  nextjs:
    build:
      context: "./"
      dockerfile: Dockerfile
    networks:
      - ship
    environment:
      REDIS_URL: redis
    volumes:
      - "./src:/app/src"
    ports:
      - "3000:3000"

    

networks:
  ship:
    name: ship_network
